version: "3.3"

services:
  authentication:
    build: authentication/.
    ports:
      - "3005:3000"
    networks:
      - backend
  registration:
    build: registration/.
    ports:
      - "3006:3000"
    networks:
      - backend
  viewpatientdata:
    build: viewpatientdata/.
    ports:
      - "3007:3000"
    networks:
      - backend
# mongo:
#     container_name: "mongo-node"
#     platform: linux/amd64
#     image: mongo:4.4.14
#     ports:
#       - "8082:8082"
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: root
#       ME_CONFIG_MONGODB_ADMINPASSWORD: root
#     networks:
#       - backend

networks:
  backend:
    driver: bridge
