version: "3.3"

services:
  authentication:
    build: authentication/.
    ports:
      - "3005:3000"
    networks:
      - backend
  registration:
    build: registration/.
    ports:
      - "3006:3000"
    networks:
      - backend
  patientdata:
    build: patientdata/.
    ports:
      - "3008:3000"
    networks:
      - backend    
  

networks:
  backend:
    driver: bridge
