version: '3.4'

services:
  lymrhospitalrami:
    image: lymrhospitalrami
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3050:3050
