apiVersion: v1
kind: Pod
metadata:
  name: authentication
  labels:
    app: authentication
spec:
  containers:
  - name: auth-cont
    image: localhost:5002/auth-im
    imagePullPolicy: Never
    ports:
    - name:  port1
      containerPort: 3000
      protocol: TCP
  
---  
apiVersion: v1
kind: Pod
metadata:
  name: registration
  labels: 
    app: registration
spec:
  containers:
  - name: reg-cont
    image: localhost:5002/reg-im
    imagePullPolicy: Never
    ports:
    - name:  port2
      containerPort: 3000
      protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: patientdata
  labels:
    app: patientdata
spec:
  containers:
  - name: pd-cont
    image: localhost:5002/pd-im
    imagePullPolicy: Never
    ports:
    - name:  port3
      containerPort: 3000
      protocol: TCP
      
---
apiVersion: v1 
kind: Service 
metadata:
  name: auth-service 
spec:
  type: NodePort
  selector:
    app: authentication
  ports:
    - nodePort: 30002
      port: 3000
      targetPort: 3000
---
apiVersion: v1 
kind: Service 
metadata:
  name: reg-service 
spec:
  type: NodePort
  selector:
    app: registration
  ports:
    - nodePort: 30003
      port: 3000
      targetPort: 3000
---
apiVersion: v1 
kind: Service 
metadata:
  name: pd-service 
spec:
  type: NodePort
  selector:
    app: patientdata
  ports:
    - nodePort: 30004
      port: 3000
      targetPort: 3000
